#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Nov 14 11:44:44 2018

@author: fredrikgarsegmork
"""

import webbrowser
from selenium import webdriver

driver=webdriver.Firefox()
driver.get("https://cloud.timeedit.net/hvl/web")
#driver=webbrowser.open("https://cloud.timeedit.net/hvl/web", new=0)
elem1=driver.find_element_by_link_text("Bergen - Student")
elem1.click()
